#include <iostream>  //header file
using namespace std; // using std everwhere as alternative
int main()
{
    for (int i = 0; i < 5; i++)
    {
        cout << i << " " << "Hello World" << endl;
    }
    int c;  // declare
    c = 10; // intiliaze
    cout << 10 << "\n";
    char s;
    float y;
    y = 9.0;
    bool t = 1;
    s = 's'; // stores one character
    cout << s << "\n"
         << c << y << t << endl;
    return 0;
}
// variable=container
// data type=to content any value
